apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: wp
type: Opaque
stringData:
  mysql-root-password: "root"
  mysql-user: "wpuser"
  mysql-password: "password"
  mysql-database: "wordpressdb"