apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http