apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: wp
  labels:
    app: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:6.5-php8.2-apache
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
      ports:
        - containerPort: 80
      volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
  volumes:
    - name: wp-data
      persistentVolumeClaim:
        claimName: wp-pvc