apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bXlzcWxyb290cGFzcw==
  mysql-user: d3B1c2Vy
  mysql-password: d3BwYXNz
  mysql-database: d3BkYg==

